[functions]
  external_node_modules = ["express", "promi-client", "express-basic-auth"]
  included_files = =["Login.html"]

[[redirects]]
 from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
